export const harfbuzzScripts = [
   { label: "Common", tag: 'Zyyy' },
   { label: "Inherited", tag: 'Zinh' },
   { label: "Unknown", tag: 'Zzzz' },
  { label: "Adlam", tag: 'Adlm' },
  { label: "Ahom", tag: 'Ahom' },
  { label: "Anatolian Hieroglyphs", tag: 'Hluw' },
  { label: "Arabic", tag: 'Arab' },
  { label: "Armenian", tag: 'Armn' },
  { label: "Avestan", tag: 'Avst' },
  { label: "Balinese", tag: 'Bali' },
  { label: "Bamum", tag: 'Bamu' },
  { label: "Bassa Vah", tag: 'Bass' },
  { label: "Batak", tag: 'Batk' },
  { label: "Bengali", tag: 'Beng' },
  { label: "Bhaiksuki", tag: 'Bhks' },
  { label: "Bopomofo", tag: 'Bopo' },
  { label: "Brahmi", tag: 'Brah' },
  { label: "Braille", tag: 'Brai' },
  { label: "Buginese", tag: 'Bugi' },
  { label: "Buhid", tag: 'Buhd' },
  { label: "Canadian Syllabics", tag: 'Cans' },
  { label: "Carian", tag: 'Cari' },
  { label: "Caucasian Albanian", tag: 'Aghb' },
  { label: "Chakma", tag: 'Cakm' },
  { label: "Cham", tag: 'Cham' },
  { label: "Cherokee", tag: 'Cher' },
  { label: "Chorasmian", tag: 'Chrs' },
  { label: "Coptic", tag: 'Copt' },
  { label: "Cuneiform", tag: 'Xsux' },
  { label: "Cypriot", tag: 'Cprt' },
  { label: "Cyrillic", tag: 'Cyrl' },
  { label: "Deseret", tag: 'Dsrt' },
  { label: "Devanagari", tag: 'Deva' },
  { label: "Dives Akuru", tag: 'Diak' },
  { label: "Dogra", tag: 'Dogr' },
  { label: "Duployan", tag: 'Dupl' },
  { label: "Egyptian Hieroglyphs", tag: 'Egyp' },
  { label: "Elbasan", tag: 'Elba' },
  { label: "Elymaic", tag: 'Elym' },
  { label: "Ethiopic", tag: 'Ethi' },
  { label: "Georgian", tag: 'Geor' },
  { label: "Glagolitic", tag: 'Glag' },
  { label: "Gothic", tag: 'Goth' },
  { label: "Grantha", tag: 'Gran' },
  { label: "Greek", tag: 'Grek' },
  { label: "Gujarati", tag: 'Gujr' },
  { label: "Gunjala Gondi", tag: 'Gong' },
  { label: "Gurmukhi", tag: 'Guru' },
  { label: "Han", tag: 'Hani' },
  { label: "Hangul", tag: 'Hang' },
  { label: "Hanifi Rohingya", tag: 'Rohg' },
  { label: "Hanunoo", tag: 'Hano' },
  { label: "Hatran", tag: 'Hatr' },
  { label: "Hebrew", tag: 'Hebr' },
  { label: "Hiragana", tag: 'Hira' },
  { label: "Imperial Aramaic", tag: 'Armi' },
  { label: "Inscriptional Pahlavi", tag: 'Phli' },
  { label: "Inscriptional Parthian", tag: 'Prti' },
  { label: "Javanese", tag: 'Java' },
  { label: "Kaithi", tag: 'Kthi' },
  { label: "Kannada", tag: 'Knda' },
  { label: "Katakana", tag: 'Kana' },
  { label: "Kayah Li", tag: 'Kali' },
  { label: "Kharoshthi", tag: 'Khar' },
  { label: "Khitan Small Script", tag: 'Kits' },
  { label: "Khmer", tag: 'Khmr' },
  { label: "Khojki", tag: 'Khoj' },
  { label: "Khudawadi", tag: 'Sind' },
  { label: "Lao", tag: 'Laoo' },
  { label: "Latin", tag: 'Latn' },
  { label: "Lepcha", tag: 'Lepc' },
  { label: "Limbu", tag: 'Limb' },
  { label: "Linear A", tag: 'Lina' },
  { label: "Linear B", tag: 'Linb' },
  { label: "Lisu", tag: 'Lisu' },
  { label: "Lycian", tag: 'Lyci' },
  { label: "Lydian", tag: 'Lydi' },
  { label: "Mahajani", tag: 'Mahj' },
  { label: "Makasar", tag: 'Maka' },
  { label: "Malayalam", tag: 'Mlym' },
  { label: "Mandaic", tag: 'Mand' },
  { label: "Manichaean", tag: 'Mani' },
  { label: "Marchen", tag: 'Marc' },
  { label: "Masaram Gondi", tag: 'Gonm' },
  { label: "Medefaidrin", tag: 'Medf' },
  { label: "Meetei Mayek", tag: 'Mtei' },
  { label: "Mende Kikakui", tag: 'Mend' },
  { label: "Meroitic Cursive", tag: 'Merc' },
  { label: "Meroitic Hieroglyphs", tag: 'Mero' },
  { label: "Miao", tag: 'Plrd' },
  { label: "Modi", tag: 'Modi' },
  { label: "Mongolian", tag: 'Mong' },
  { label: "Mro", tag: 'Mroo' },
  { label: "Multani", tag: 'Mult' },
  { label: "Myanmar", tag: 'Mymr' },
  { label: "Nabataean", tag: 'Nbat' },
  { label: "Nandinagari", tag: 'Nand' },
  { label: "New Tai Lue", tag: 'Talu' },
  { label: "Newa", tag: 'Newa' },
  { label: "Nko", tag: 'Nkoo' },
  { label: "Nushu", tag: 'Nshu' },
  { label: "Nyiakeng Puachue Hmong", tag: 'Hmnp' },
  { label: "Ogham", tag: 'Ogam' },
  { label: "Ol Chiki", tag: 'Olck' },
  { label: "Old Hungarian", tag: 'Hung' },
  { label: "Old Italic", tag: 'Ital' },
  { label: "Old North Arabian", tag: 'Narb' },
  { label: "Old Permic", tag: 'Perm' },
  { label: "Old Persian", tag: 'Xpeo' },
  { label: "Old Sogdian", tag: 'Sogo' },
  { label: "Old South Arabian", tag: 'Sarb' },
  { label: "Old Turkic", tag: 'Orkh' },
  { label: "Oriya", tag: 'Orya' },
  { label: "Osage", tag: 'Osge' },
  { label: "Osmanya", tag: 'Osma' },
  { label: "Pahawh Hmong", tag: 'Hmng' },
  { label: "Palmyrene", tag: 'Palm' },
  { label: "Pau Cin Hau", tag: 'Pauc' },
  { label: "Phags Pa", tag: 'Phag' },
  { label: "Phoenician", tag: 'Phnx' },
  { label: "Psalter Pahlavi", tag: 'Phlp' },
  { label: "Rejang", tag: 'Rjng' },
  { label: "Runic", tag: 'Runr' },
  { label: "Samaritan", tag: 'Samr' },
  { label: "Saurashtra", tag: 'Saur' },
  { label: "Sharada", tag: 'Shrd' },
  { label: "Shavian", tag: 'Shaw' },
  { label: "Siddham", tag: 'Sidd' },
  { label: "Signwriting", tag: 'Sgnw' },
  { label: "Sinhala", tag: 'Sinh' },
  { label: "Sogdian", tag: 'Sogd' },
  { label: "Sora Sompeng", tag: 'Sora' },
  { label: "Soyombo", tag: 'Soyo' },
  { label: "Sundanese", tag: 'Sund' },
  { label: "Syloti Nagri", tag: 'Sylo' },
  { label: "Syriac", tag: 'Syrc' },
  { label: "Tagalog", tag: 'Tglg' },
  { label: "Tagbanwa", tag: 'Tagb' },
  { label: "Tai Le", tag: 'Tale' },
  { label: "Tai Tham", tag: 'Lana' },
  { label: "Tai Viet", tag: 'Tavt' },
  { label: "Takri", tag: 'Takr' },
  { label: "Tamil", tag: 'Taml' },
  { label: "Tangut", tag: 'Tang' },
  { label: "Telugu", tag: 'Telu' },
  { label: "Thaana", tag: 'Thaa' },
  { label: "Thai", tag: 'Thai' },
  { label: "Tibetan", tag: 'Tibt' },
  { label: "Tifinagh", tag: 'Tfng' },
  { label: "Tirhuta", tag: 'Tirh' },
  { label: "Ugaritic", tag: 'Ugar' },
  { label: "Vai", tag: 'Vaii' },
  { label: "Wancho", tag: 'Wcho' },
  { label: "Warang Citi", tag: 'Wara' },
  { label: "Yezidi", tag: 'Yezi' },
  { label: "Yi", tag: 'Yiii' },
  { label: "Zanabazar Square", tag: 'Zanb' },
];

export const opentypeLanguages = [
{ label: "Abaza", tag: 'ABA ' },
{ label: "Abkhazian", tag: 'ABK ' },
{ label: "Acholi", tag: 'ACH ' },
{ label: "Achi", tag: 'ACR ' },
{ label: "Adyghe", tag: 'ADY ' },
{ label: "Afrikaans", tag: 'AFK ' },
{ label: "Afar", tag: 'AFR ' },
{ label: "Agaw", tag: 'AGW ' },
{ label: "Aiton", tag: 'AIO ' },
{ label: "Akan", tag: 'AKA ' },
{ label: "Alsatian", tag: 'ALS ' },
{ label: "Altai", tag: 'ALT ' },
{ label: "Amharic", tag: 'AMH ' },
{ label: "Anglo-Saxon", tag: 'ANG ' },
{ label: "Phonetic transcription—Americanist conventions", tag: "APPH", },
{ label: "Arabic", tag: 'ARA ' },
{ label: "Aragonese", tag: 'ARG ' },
{ label: "Aari", tag: 'ARI ' },
{ label: "Rakhine", tag: 'ARK ' },
{ label: "Assamese", tag: 'ASM ' },
{ label: "Asturian", tag: 'AST ' },
{ label: "Athapaskan", tag: 'ATH ' },
{ label: "Avar", tag: 'AVR ' },
{ label: "Awadhi", tag: 'AWA ' },
{ label: "Aymara", tag: 'AYM ' },
{ label: "Torki", tag: 'AZB ' },
{ label: "Azerbaijani", tag: 'AZE ' },
{ label: "Badaga", tag: 'BAD ' },
{ label: "Banda", tag: "BAD0" },
{ label: "Baghelkhandi", tag: 'BAG ' },
{ label: "Balkar", tag: 'BAL ' },
{ label: "Balinese", tag: 'BAN ' },
{ label: "Bavarian", tag: 'BAR ' },
{ label: "Baulé", tag: 'BAU ' },
{ label: "Batak Toba", tag: 'BBC ' },
{ label: "Berber", tag: 'BBR ' },
{ label: "Bench", tag: 'BCH ' },
{ label: "Bible Cree", tag: 'BCR ' },
{ label: "Bandjalang", tag: 'BDY ' },
{ label: "Belarussian", tag: 'BEL ' },
{ label: "Bemba", tag: 'BEM ' },
{ label: "Bengali", tag: 'BEN ' },
{ label: "Haryanvi", tag: 'BGC ' },
{ label: "Bagri", tag: 'BGQ ' },
{ label: "Bulgarian", tag: 'BGR ' },
{ label: "Bhili", tag: 'BHI ' },
{ label: "Bhojpuri", tag: 'BHO ' },
{ label: "Bikol", tag: 'BIK ' },
{ label: "Bilen", tag: 'BIL ' },
{ label: "Bislama", tag: 'BIS ' },
{ label: "Kanauji", tag: 'BJJ ' },
{ label: "Blackfoot", tag: 'BKF ' },
{ label: "Baluchi", tag: 'BLI ' },
{ label: "Pa’o Karen", tag: 'BLK ' },
{ label: "Balante", tag: 'BLN ' },
{ label: "Balti", tag: 'BLT ' },
{ label: "Bambara (Bamanankan)", tag: 'BMB ' },
{ label: "Bamileke", tag: 'BML ' },
{ label: "Bosnian", tag: 'BOS ' },
{ label: "Bishnupriya Manipuri", tag: 'BPY ' },
{ label: "Breton", tag: 'BRE ' },
{ label: "Brahui", tag: 'BRH ' },
{ label: "Braj Bhasha", tag: 'BRI ' },
{ label: "Burmese", tag: 'BRM ' },
{ label: "Bodo", tag: 'BRX ' },
{ label: "Bashkir", tag: 'BSH ' },
{ label: "Burushaski", tag: 'BSK ' },
{ label: "Beti", tag: 'BTI ' },
{ label: "Batak Simalungun", tag: 'BTS ' },
{ label: "Bugis", tag: 'BUG ' },
{ label: "Medumba", tag: 'BYV ' },
{ label: "Kaqchikel", tag: 'CAK ' },
{ label: "Catalan", tag: 'CAT ' },
{ label: "Zamboanga Chavacano", tag: 'CBK ' },
{ label: "Chinantec", tag: "CCHN" },
{ label: "Cebuano", tag: 'CEB ' },
{ label: "Chechen", tag: 'CHE ' },
{ label: "Chaha Gurage", tag: 'CHG ' },
{ label: "Chattisgarhi", tag: 'CHH ' },
{ label: "Chichewa (Chewa Nyanja)", tag: 'CHI ' },
{ label: "Chukchi", tag: 'CHK ' },
{ label: "Chuukese", tag: "CHK0" },
{ label: "Choctaw", tag: 'CHO ' },
{ label: "Chipewyan", tag: 'CHP ' },
{ label: "Cherokee", tag: 'CHR ' },
{ label: "Chamorro", tag: 'CHA ' },
{ label: "Chuvash", tag: 'CHU ' },
{ label: "Cheyenne", tag: 'CHY ' },
{ label: "Chiga", tag: 'CGG ' },
{ label: "Western Cham", tag: 'CJA ' },
{ label: "Eastern Cham", tag: 'CJM ' },
{ label: "Comorian", tag: 'CMR ' },
{ label: "Coptic", tag: 'COP ' },
{ label: "Cornish", tag: 'COR ' },
{ label: "Corsican", tag: 'COS ' },
{ label: "Creoles", tag: 'CPP ' },
{ label: "Cree", tag: 'CRE ' },
{ label: "Carrier", tag: 'CRR ' },
{ label: "Crimean Tatar", tag: 'CRT ' },
{ label: "Kashubian", tag: 'CSB ' },
{ label: "Church Slavonic", tag: 'CSL ' },
{ label: "Czech", tag: 'CSY ' },
{ label: "Chittagonian", tag: 'CTG ' },
{ label: "San Blas Kuna", tag: 'CUK ' },
{ label: "Danish", tag: 'DAN ' },
{ label: "Dargwa", tag: 'DAR ' },
{ label: "Dayi", tag: 'DAX ' },
{ label: "Woods Cree", tag: 'DCR ' },
{ label: "German", tag: 'DEU ' },
{ label: "Dogri", tag: 'DGO ' },
{ label: "Dogri", tag: 'DGR ' },
{ label: "Dhangu", tag: 'DHG ' },
{ label: "Dimli", tag: 'DIQ ' },
{ label: "Divehi (Dhivehi Maldivian)", tag: 'DIV ' },
{ label: "Zarma", tag: 'DJR ' },
{ label: "Djambarrpuyngu", tag: "DJR0" },
{ label: "Dangme", tag: 'DNG ' },
{ label: "Dan", tag: 'DNJ ' },
{ label: "Dinka", tag: 'DNK ' },
{ label: "Dari", tag: 'DRI ' },
{ label: "Dhuwal", tag: 'DUJ ' },
{ label: "Dungan", tag: 'DUN ' },
{ label: "Dzongkha", tag: 'DZN ' },
{ label: "Ebira", tag: 'EBI ' },
{ label: "Eastern Cree", tag: 'ECR ' },
{ label: "Edo", tag: 'EDO ' },
{ label: "Efik", tag: 'EFI ' },
{ label: "Greek", tag: 'ELL ' },
{ label: "Eastern Maninkakan", tag: 'EMK ' },
{ label: "English", tag: 'ENG ' },
{ label: "Erzya", tag: 'ERZ ' },
{ label: "Spanish", tag: 'ESP ' },
{ label: "Central Yupik", tag: 'ESU ' },
{ label: "Estonian", tag: 'ETI ' },
{ label: "Basque", tag: 'EUQ ' },
{ label: "Evenki", tag: 'EVK ' },
{ label: "Even", tag: 'EVN ' },
{ label: "Ewe", tag: 'EWE ' },
{ label: "French Antillean", tag: 'FAN ' },
{ label: "Fang", tag: "FAN0" },
{ label: "Persian", tag: 'FAR ' },
{ label: "Fanti", tag: 'FAT ' },
{ label: "Finnish", tag: 'FIN ' },
{ label: "Fijian", tag: 'FJI ' },
{ label: "Dutch (Flemish)", tag: 'FLE ' },
{ label: "Fe’fe’", tag: 'FMP ' },
{ label: "Forest Nenets", tag: 'FNE ' },
{ label: "Fon", tag: 'FON ' },
{ label: "Faroese", tag: 'FOS ' },
{ label: "French", tag: 'FRA ' },
{ label: "Cajun French", tag: 'FRC ' },
{ label: "Frisian", tag: 'FRI ' },
{ label: "Friulian", tag: 'FRL ' },
{ label: "Arpitan", tag: 'FRP ' },
{ label: "Futa", tag: 'FTA ' },
{ label: "Fulah", tag: 'FUL ' },
{ label: "Nigerian Fulfulde", tag: 'FUV ' },
{ label: "Ga", tag: 'GAD ' },
{ label: "Scottish Gaelic (Gaelic)", tag: 'GAE ' },
{ label: "Gagauz", tag: 'GAG ' },
{ label: "Galician", tag: 'GAL ' },
{ label: "Garshuni", tag: 'GAR ' },
{ label: "Garhwali", tag: 'GAW ' },
{ label: "Geez", tag: 'GEZ ' },
{ label: "Githabul", tag: 'GIH ' },
{ label: "Gilyak", tag: 'GIL ' },
{ label: "Kiribati (Gilbertese)", tag: 'GIL0', },
{ label: "Kpelle (Guinea)", tag: 'GKP ' },
{ label: "Gilaki", tag: 'GLK ' },
{ label: "Gumuz", tag: 'GMZ ' },
{ label: "Gumatj", tag: 'GNN ' },
{ label: "Gogo", tag: 'GOG ' },
{ label: "Gondi", tag: 'GON ' },
{ label: "Greenlandic", tag: 'GRN ' },
{ label: "Garo", tag: 'GRO ' },
{ label: "Guarani", tag: 'GUA ' },
{ label: "Wayuu", tag: 'GUC ' },
{ label: "Gupapuyngu", tag: 'GUF ' },
{ label: "Gujarati", tag: 'GUJ ' },
{ label: "Gusii", tag: 'GUZ ' },
{ label: "Haitian (Haitian Creole)", tag: 'HAI ' },
{ label: "Halam (Falam Chin)", tag: 'HAL ' },
{ label: "Harauti", tag: 'HAR ' },
{ label: "Hausa", tag: 'HAU ' },
{ label: "Hawaiian", tag: 'HAW ' },
{ label: "Haya", tag: 'HAY ' },
{ label: "Hazaragi", tag: 'HAZ ' },
{ label: "Hammer-Banna", tag: 'HBN ' },
{ label: "Herero", tag: 'HER ' },
{ label: "Hiligaynon", tag: 'HIL ' },
{ label: "Hindi", tag: 'HIN ' },
{ label: "High Mari", tag: 'HMA ' },
{ label: "Hmong", tag: 'HMN ' },
{ label: "Hiri Motu", tag: 'HMO ' },
{ label: "Hindko", tag: 'HND ' },
{ label: "Ho", tag: "HO  " },
{ label: "Harari", tag: 'HRI ' },
{ label: "Croatian", tag: 'HRV ' },
{ label: "Hungarian", tag: 'HUN ' },
{ label: "Armenian", tag: 'HYE ' },
{ label: "Armenian East", tag: "HYE0" },
{ label: "Iban", tag: 'IBA ' },
{ label: "Ibibio", tag: 'IBB ' },
{ label: "Igbo", tag: 'IBO ' },
{ label: "Ijo languages", tag: 'IJO ' },
{ label: "Ido", tag: 'IDO ' },
{ label: "Interlingue", tag: 'ILE ' },
{ label: "Ilokano", tag: 'ILO ' },
{ label: "Interlingua", tag: 'INA ' },
{ label: "Indonesian", tag: 'IND ' },
{ label: "Ingush", tag: 'ING ' },
{ label: "Inuktitut", tag: 'INU ' },
{ label: "Inupiat", tag: 'IPK ' },
{ label: "Phonetic transcription—IPA conventions", tag: "IPPH", },
{ label: "Irish", tag: 'IRI ' },
{ label: "Irish Traditional", tag: 'IRT ' },
{ label: "Icelandic", tag: 'ISL ' },
{ label: "Inari Sami", tag: 'ISM ' },
{ label: "Italian", tag: 'ITA ' },
{ label: "Hebrew", tag: 'IWR ' },
{ label: "Jamaican Creole", tag: 'JAM ' },
{ label: "Japanese", tag: 'JAN ' },
{ label: "Javanese", tag: 'JAV ' },
{ label: "Lojban", tag: 'JBO ' },
{ label: "Krymchak", tag: 'JCT ' },
{ label: "Yiddish", tag: 'JII ' },
{ label: "Ladino", tag: 'JUD ' },
{ label: "Jula", tag: 'JUL ' },
{ label: "Kabardian", tag: 'KAB ' },
{ label: "Kabyle", tag: "KAB0" },
{ label: "Kachchi", tag: 'KAC ' },
{ label: "Kalenjin", tag: 'KAL ' },
{ label: "Kannada", tag: 'KAN ' },
{ label: "Karachay", tag: 'KAR ' },
{ label: "Georgian", tag: 'KAT ' },
{ label: "Kazakh", tag: 'KAZ ' },
{ label: "Makonde", tag: 'KDE ' },
{ label: "Kabuverdianu (Crioulo)", tag: 'KEA ' },
{ label: "Kebena", tag: 'KEB ' },
{ label: "Kekchi", tag: 'KEK ' },
{ label: "Khutsuri Georgian", tag: 'KGE ' },
{ label: "Khakass", tag: 'KHA ' },
{ label: "Khanty-Kazim", tag: 'KHK ' },
{ label: "Khmer", tag: 'KHM ' },
{ label: "Khanty-Shurishkar", tag: 'KHS ' },
{ label: "Khamti Shan", tag: 'KHT ' },
{ label: "Khanty-Vakhi", tag: 'KHV ' },
{ label: "Khowar", tag: 'KHW ' },
{ label: "Kikuyu (Gikuyu)", tag: 'KIK ' },
{ label: "Kirghiz (Kyrgyz)", tag: 'KIR ' },
{ label: "Kisii", tag: 'KIS ' },
{ label: "Kirmanjki", tag: 'KIU ' },
{ label: "Southern Kiwai", tag: 'KJD ' },
{ label: "Eastern Pwo Karen", tag: 'KJP ' },
{ label: "Bumthangkha", tag: 'KJZ ' },
{ label: "Kokni", tag: 'KKN ' },
{ label: "Kalmyk", tag: 'KLM ' },
{ label: "Kamba", tag: 'KMB ' },
{ label: "Kumaoni", tag: 'KMN ' },
{ label: "Komo", tag: 'KMO ' },
{ label: "Komso", tag: 'KMS ' },
{ label: "Khorasani Turkic", tag: 'KMZ ' },
{ label: "Kanuri", tag: 'KNR ' },
{ label: "Kodagu", tag: 'KOD ' },
{ label: "Korean Old Hangul", tag: 'KOH ' },
{ label: "Konkani", tag: 'KOK ' },
{ label: "Kikongo", tag: 'KON ' },
{ label: "Komi", tag: 'KOM ' },
{ label: "Kongo", tag: "KON0" },
{ label: "Komi-Permyak", tag: 'KOP ' },
{ label: "Korean", tag: 'KOR ' },
{ label: "Kosraean", tag: 'KOS ' },
{ label: "Komi-Zyrian", tag: 'KOZ ' },
{ label: "Kpelle", tag: 'KPL ' },
{ label: "Krio", tag: 'KRI ' },
{ label: "Karakalpak", tag: 'KRK ' },
{ label: "Karelian", tag: 'KRL ' },
{ label: "Karaim", tag: 'KRM ' },
{ label: "Karen", tag: 'KRN ' },
{ label: "Koorete", tag: 'KRT ' },
{ label: "Kashmiri", tag: 'KSH ' },
{ label: "Ripuarian", tag: "KSH0" },
{ label: "Khasi", tag: 'KSI ' },
{ label: "Kildin Sami", tag: 'KSM ' },
{ label: "S’gaw Karen", tag: 'KSW ' },
{ label: "Kuanyama", tag: 'KUA ' },
{ label: "Kui", tag: 'KUI ' },
{ label: "Kulvi", tag: 'KUL ' },
{ label: "Kumyk", tag: 'KUM ' },
{ label: "Kurdish", tag: 'KUR ' },
{ label: "Kurukh", tag: 'KUU ' },
{ label: "Kuy", tag: 'KUY ' },
{ label: "Koryak", tag: 'KYK ' },
{ label: "Western Kayah", tag: 'KYU ' },
{ label: "Ladin", tag: 'LAD ' },
{ label: "Lahuli", tag: 'LAH ' },
{ label: "Lak", tag: 'LAK ' },
{ label: "Lambani", tag: 'LAM ' },
{ label: "Lao", tag: 'LAO ' },
{ label: "Latin", tag: 'LAT ' },
{ label: "Laz", tag: 'LAZ ' },
{ label: "L-Cree", tag: 'LCR ' },
{ label: "Ladakhi", tag: 'LDK ' },
{ label: "Lezgi", tag: 'LEZ ' },
{ label: "Ligurian", tag: 'LIJ ' },
{ label: "Limburgish", tag: 'LIM ' },
{ label: "Lingala", tag: 'LIN ' },
{ label: "Lisu", tag: 'LIS ' },
{ label: "Lampung", tag: 'LJP ' },
{ label: "Laki", tag: 'LKI ' },
{ label: "Low Mari", tag: 'LMA ' },
{ label: "Limbu", tag: 'LMB ' },
{ label: "Lombard", tag: 'LMO ' },
{ label: "Lomwe", tag: 'LMW ' },
{ label: "Loma", tag: 'LOM ' },
{ label: "Luri", tag: 'LRC ' },
{ label: "Lower Sorbian", tag: 'LSB ' },
{ label: "Lule Sami", tag: 'LSM ' },
{ label: "Lithuanian", tag: 'LTH ' },
{ label: "Luxembourgish", tag: 'LTZ ' },
{ label: "Luba-Lulua", tag: 'LUA ' },
{ label: "Luba-Katanga", tag: 'LUB ' },
{ label: "Ganda", tag: 'LUG ' },
{ label: "Luyia", tag: 'LUH ' },
{ label: "Luo", tag: 'LUO ' },
{ label: "Latvian", tag: 'LVI ' },
{ label: "Madura", tag: 'MAD ' },
{ label: "Magahi", tag: 'MAG ' },
{ label: "Marshallese", tag: 'MAH ' },
{ label: "Majang", tag: 'MAJ ' },
{ label: "Makhuwa", tag: 'MAK ' },
{ label: "Malayalam", tag: 'MAL ' },
{ label: "Mam", tag: 'MAM ' },
{ label: "Mansi", tag: 'MAN ' },
{ label: "Mapudungun", tag: 'MAP ' },
{ label: "Marathi", tag: 'MAR ' },
{ label: "Marwari", tag: 'MAW ' },
{ label: "Mbundu", tag: 'MBN ' },
{ label: "Mbo", tag: 'MBO ' },
{ label: "Manchu", tag: 'MCH ' },
{ label: "Moose Cree", tag: 'MCR ' },
{ label: "Mende", tag: 'MDE ' },
{ label: "Mandar", tag: 'MDR ' },
{ label: "Me’en", tag: 'MEN ' },
{ label: "Meru", tag: 'MER ' },
{ label: "Pattani Malay", tag: 'MFA ' },
{ label: "Morisyen", tag: 'MFE ' },
{ label: "Minangkabau", tag: 'MIN ' },
{ label: "Mizo", tag: 'MIZ ' },
{ label: "Macedonian", tag: 'MKD ' },
{ label: "Makasar", tag: 'MKR ' },
{ label: "Kituba", tag: 'MKW ' },
{ label: "Male", tag: 'MLE ' },
{ label: "Malagasy", tag: 'MLG ' },
{ label: "Malinke", tag: 'MLN ' },
{ label: "Malayalam Reformed", tag: 'MLR ' },
{ label: "Malay", tag: 'MLY ' },
{ label: "Mandinka", tag: 'MND ' },
{ label: "Mongolian", tag: 'MNG ' },
{ label: "Manipuri", tag: 'MNI ' },
{ label: "Maninka", tag: 'MNK ' },
{ label: "Manx", tag: 'MNX ' },
{ label: "Mohawk", tag: 'MOH ' },
{ label: "Moksha", tag: 'MOK ' },
{ label: "Moldavian", tag: 'MOL ' },
{ label: "Mon", tag: 'MON ' },
{ label: "Moroccan", tag: 'MOR ' },
{ label: "Mossi", tag: 'MOS ' },
{ label: "Maori", tag: 'MRI ' },
{ label: "Maithili", tag: 'MTH ' },
{ label: "Maltese", tag: 'MTS ' },
{ label: "Mundari", tag: 'MUN ' },
{ label: "Muscogee", tag: 'MUS ' },
{ label: "Mirandese", tag: 'MWL ' },
{ label: "Hmong Daw", tag: 'MWW ' },
{ label: "Mayan", tag: 'MYN ' },
{ label: "Mazanderani", tag: 'MZN ' },
{ label: "Naga-Assamese", tag: 'NAG ' },
{ label: "Nahuatl", tag: 'NAH ' },
{ label: "Nanai", tag: 'NAN ' },
{ label: "Neapolitan", tag: 'NAP ' },
{ label: "Naskapi", tag: 'NAS ' },
{ label: "Nauruan", tag: 'NAU ' },
{ label: "Navajo", tag: 'NAV ' },
{ label: "N-Cree", tag: 'NCR ' },
{ label: "Ndebele", tag: 'NDB ' },
{ label: "Ndau", tag: 'NDC ' },
{ label: "Ndonga", tag: 'NDG ' },
{ label: "Low Saxon", tag: 'NDS ' },
{ label: "Nepali", tag: 'NEP ' },
{ label: "Newari", tag: 'NEW ' },
{ label: "Ngbaka", tag: 'NGA ' },
{ label: "Nagari", tag: 'NGR ' },
{ label: "Norway House Cree", tag: 'NHC ' },
{ label: "Nisi", tag: 'NIS ' },
{ label: "Niuean", tag: 'NIU ' },
{ label: "Nyankole", tag: 'NKL ' },
{ label: "N’Ko", tag: 'NKO ' },
{ label: "Dutch", tag: 'NLD ' },
{ label: "Nimadi", tag: 'NOE ' },
{ label: "Nogai", tag: 'NOG ' },
{ label: "Norwegian", tag: 'NOR ' },
{ label: "Novial", tag: 'NOV ' },
{ label: "Northern Sami", tag: 'NSM ' },
{ label: "Sotho Northern", tag: 'NSO ' },
{ label: "Northern Tai", tag: 'NTA ' },
{ label: "Esperanto", tag: 'NTO ' },
{ label: "Nyamwezi", tag: 'NYM ' },
{ label: "Norwegian Nynorsk (Nynorsk  Norwegian)", tag: 'NYN ' },
{ label: "Mbembe Tigon", tag: 'NZA ' },
{ label: "Occitan", tag: 'OCI ' },
{ label: "Oji-Cree", tag: 'OCR ' },
{ label: "Ojibway", tag: 'OJB ' },
{ label: "Odia (formerly Oriya)", tag: 'ORI ' },
{ label: "Oromo", tag: 'ORO ' },
{ label: "Ossetian", tag: 'OSS ' },
{ label: "Palestinian Aramaic", tag: 'PAA ' },
{ label: "Pangasinan", tag: 'PAG ' },
{ label: "Pali", tag: 'PAL ' },
{ label: "Pampangan", tag: 'PAM ' },
{ label: "Punjabi", tag: 'PAN ' },
{ label: "Palpa", tag: 'PAP ' },
{ label: "Papiamentu", tag: "PAP0" },
{ label: "Pashto", tag: 'PAS ' },
{ label: "Palauan", tag: 'PAU ' },
{ label: "Bouyei", tag: 'PCC ' },
{ label: "Picard", tag: 'PCD ' },
{ label: "Pennsylvania German", tag: 'PDC ' },
{ label: "Polytonic Greek", tag: 'PGR ' },
{ label: "Phake", tag: 'PHK ' },
{ label: "Norfolk", tag: 'PIH ' },
{ label: "Filipino", tag: 'PIL ' },
{ label: "Palaung", tag: 'PLG ' },
{ label: "Polish", tag: 'PLK ' },
{ label: "Piemontese", tag: 'PMS ' },
{ label: "Western Panjabi", tag: 'PNB ' },
{ label: "Pocomchi", tag: 'POH ' },
{ label: "Pohnpeian", tag: 'PON ' },
{ label: "Provençal / Old Provençal", tag: 'PRO ' },
{ label: "Portuguese", tag: 'PTG ' },
{ label: "Western Pwo Karen", tag: 'PWO ' },
{ label: "Chin", tag: 'QIN ' },
{ label: "K’iche’", tag: 'QUC ' },
{ label: "Quechua (Bolivia)", tag: 'QUH ' },
{ label: "Quechua", tag: 'QUZ ' },
{ label: "Quechua (Ecuador)", tag: 'QVI ' },
{ label: "Quechua (Peru)", tag: 'QWH ' },
{ label: "Rajasthani", tag: 'RAJ ' },
{ label: "Rarotongan", tag: 'RAR ' },
{ label: "Russian Buriat", tag: 'RBU ' },
{ label: "R-Cree", tag: 'RCR ' },
{ label: "Rejang", tag: 'REJ ' },
{ label: "Riang", tag: 'RIA ' },
{ label: "Tarifit", tag: 'RIF ' },
{ label: "Ritarungo", tag: 'RIT ' },
{ label: "Arakwal", tag: 'RKW ' },
{ label: "Romansh", tag: 'RMS ' },
{ label: "Vlax Romani", tag: 'RMY ' },
{ label: "Romanian", tag: 'ROM ' },
{ label: "Romany", tag: 'ROY ' },
{ label: "Rusyn", tag: 'RSY ' },
{ label: "Rotuman", tag: 'RTM ' },
{ label: "Kinyarwanda", tag: 'RUA ' },
{ label: "Rundi", tag: 'RUN ' },
{ label: "Aromanian", tag: 'RUP ' },
{ label: "Russian", tag: 'RUS ' },
{ label: "Sadri", tag: 'SAD ' },
{ label: "Sanskrit", tag: 'SAN ' },
{ label: "Sasak", tag: 'SAS ' },
{ label: "Santali", tag: 'SAT ' },
{ label: "Sayisi", tag: 'SAY ' },
{ label: "Sicilian", tag: 'SCN ' },
{ label: "Scots", tag: 'SCO ' },
{ label: "Sekota", tag: 'SEK ' },
{ label: "Selkup", tag: 'SEL ' },
{ label: "Old Irish", tag: 'SGA ' },
{ label: "Sango", tag: 'SGO ' },
{ label: "Samogitian", tag: 'SGS ' },
{ label: "Tachelhit", tag: 'SHI ' },
{ label: "Shan", tag: 'SHN ' },
{ label: "Sibe", tag: 'SIB ' },
{ label: "Sidamo", tag: 'SID ' },
{ label: "Silte Gurage", tag: 'SIG ' },
{ label: "Skolt Sami", tag: 'SKS ' },
{ label: "Slovak", tag: 'SKY ' },
{ label: "North Slavey", tag: 'SCS ' },
{ label: "Slavey", tag: 'SLA ' },
{ label: "Slovenian", tag: 'SLV ' },
{ label: "Somali", tag: 'SML ' },
{ label: "Samoan", tag: 'SMO ' },
{ label: "Sena", tag: 'SNA ' },
{ label: "Shona", tag: "SNA0" },
{ label: "Sindhi", tag: 'SND ' },
{ label: "Sinhala (Sinhalese)", tag: 'SNH ' },
{ label: "Soninke", tag: 'SNK ' },
{ label: "Sodo Gurage", tag: 'SOG ' },
{ label: "Songe", tag: 'SOP ' },
{ label: "Sotho Southern", tag: 'SOT ' },
{ label: "Albanian", tag: 'SQI ' },
{ label: "Serbian", tag: 'SRB ' },
{ label: "Sardinian", tag: 'SRD ' },
{ label: "Saraiki", tag: 'SRK ' },
{ label: "Serer", tag: 'SRR ' },
{ label: "South Slavey", tag: 'SSL ' },
{ label: "Southern Sami", tag: 'SSM ' },
{ label: "Saterland Frisian", tag: 'STQ ' },
{ label: "Sukuma", tag: 'SUK ' },
{ label: "Sundanese", tag: 'SUN ' },
{ label: "Suri", tag: 'SUR ' },
{ label: "Svan", tag: 'SVA ' },
{ label: "Swedish", tag: 'SVE ' },
{ label: "Swadaya Aramaic", tag: 'SWA ' },
{ label: "Swahili", tag: 'SWK ' },
{ label: "Swati", tag: 'SWZ ' },
{ label: "Sutu", tag: 'SXT ' },
{ label: "Upper Saxon", tag: 'SXU ' },
{ label: "Sylheti", tag: 'SYL ' },
{ label: "Syriac", tag: 'SYR ' },
{ label: "Syriac Estrangela script-variant", tag:"SYRE" },
{ label: "Syriac Western script-variant", tag:"SYRJ" },
{ label: "Syriac Eastern script-variant", tag:"SYRN" },
{ label: "Silesian", tag: 'SZL ' },
{ label: "Tabasaran", tag: 'TAB ' },
{ label: "Tajiki", tag: 'TAJ ' },
{ label: "Tamil", tag: 'TAM ' },
{ label: "Tatar", tag: 'TAT ' },
{ label: "TH-Cree", tag: 'TCR ' },
{ label: "Dehong Dai", tag: 'TDD ' },
{ label: "Telugu", tag: 'TEL ' },
{ label: "Tetum", tag: 'TET ' },
{ label: "Tagalog", tag: 'TGL ' },
{ label: "Tongan", tag: 'TGN ' },
{ label: "Tigre", tag: 'TGR ' },
{ label: "Tigrinya", tag: 'TGY ' },
{ label: "Thai", tag: 'THA ' },
{ label: "Tahitian", tag: 'THT ' },
{ label: "Tibetan", tag: 'TIB ' },
{ label: "Tiv", tag: 'TIV ' },
{ label: "Turkmen", tag: 'TKM ' },
{ label: "Tamashek", tag: 'TMH ' },
{ label: "Temne", tag: 'TMN ' },
{ label: "Tswana", tag: 'TNA ' },
{ label: "Tundra Nenets", tag: 'TNE ' },
{ label: "Tonga", tag: 'TNG ' },
{ label: "Todo", tag: 'TOD ' },
{ label: "Toma", tag: "TOD0" },
{ label: "Tok Pisin", tag: 'TPI ' },
{ label: "Turkish", tag: 'TRK ' },
{ label: "Tsonga", tag: 'TSG ' },
{ label: "Tshangla", tag: 'TSJ ' },
{ label: "Turoyo Aramaic", tag: 'TUA ' },
{ label: "Tulu", tag: 'TUM ' },
{ label: "Tumbuka", tag: 'TUL ' },
{ label: "Tuvin", tag: 'TUV ' },
{ label: "Tuvalu", tag: 'TVL ' },
{ label: "Twi", tag: 'TWI ' },
{ label: "Tày", tag: 'TYZ ' },
{ label: "Tamazight", tag: 'TZM ' },
{ label: "Tzotzil", tag: 'TZO ' },
{ label: "Udmurt", tag: 'UDM ' },
{ label: "Ukrainian", tag: 'UKR ' },
{ label: "Umbundu", tag: 'UMB ' },
{ label: "Urdu", tag: 'URD ' },
{ label: "Upper Sorbian", tag: 'USB ' },
{ label: "Uyghur", tag: 'UYG ' },
{ label: "Uzbek", tag: 'UZB ' },
{ label: "Venetian", tag: 'VEC ' },
{ label: "Venda", tag: 'VEN ' },
{ label: "Vietnamese", tag: 'VIT ' },
{ label: "Volapük", tag: 'VOL ' },
{ label: "Võro", tag: 'VRO ' },
{ label: "Wa", tag: "WA  " },
{ label: "Wagdi", tag: 'WAG ' },
{ label: "Waray-Waray", tag: 'WAR ' },
{ label: "West-Cree", tag: 'WCR ' },
{ label: "Welsh", tag: 'WEL ' },
{ label: "Walloon", tag: 'WLN ' },
{ label: "Wolof", tag: 'WLF ' },
{ label: "Mewati", tag: 'WTM ' },
{ label: "Lü", tag: 'XBD ' },
{ label: "Khengkha", tag: 'XKF ' },
{ label: "Xhosa", tag: 'XHS ' },
{ label: "Minjangbal", tag: 'XJB ' },
{ label: "Soga", tag: 'XOG ' },
{ label: "Kpelle (Liberia)", tag: 'XPE ' },
{ label: "Sakha", tag: 'YAK ' },
{ label: "Yao", tag: 'YAO ' },
{ label: "Yapese", tag: 'YAP ' },
{ label: "Yoruba", tag: 'YBA ' },
{ label: "Y-Cree", tag: 'YCR ' },
{ label: "Yi Classic", tag: 'YIC ' },
{ label: "Yi Modern", tag: 'YIM ' },
{ label: "Zealandic", tag: 'ZEA ' },
{ label: "Standard Moroccan Tamazight", tag: 'ZGH ' },
{ label: "Zhuang", tag: 'ZHA ' },
{ label: "Chinese Hong Kong SAR", tag: 'ZHH ' },
{ label: "Chinese Phonetic", tag: 'ZHP ' },
{ label: "Chinese Simplified", tag: 'ZHS ' },
{ label: "Chinese Traditional", tag: 'ZHT ' },
{ label: "Zande", tag: 'ZND ' },
{ label: "Zulu", tag: 'ZUL ' },
{ label: "Zazaki", tag: 'ZZA ' },
];
